name: Run Newman Collection

on:
  schedule:
    - cron: '30 8 * * 1-5' # Rodar de segunda a sexta às 8:30 da manhã (UTC)

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código no repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalar o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Versão do Node.js

      # Instalar Newman, htmlextra reporter e Allure
      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra allure-commandline

      # Executar a coleção do Postman com o Newman, reporter htmlextra e variáveis de ambiente
      - name: Run Newman Collection
        run: |
          newman run Pix-Pipeline.postman_collection.json \
          --environment Orbitall.postman_environment.json \
          -r htmlextra --reporter-htmlextra-export newman-report.html

      # Fazer upload do relatório gerado como um artefato
      - name: Upload Newman Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman-report.html
